const products = [
  {id:'espresso',name:'Espresso',category:'coffee',price:3.5,icon:'☕',tag:'Bold & smooth',description:'A rich, balanced little pick-me-up.'},
  {id:'latte',name:'Honey Oat Latte',category:'coffee',price:5.75,icon:'🥛',tag:'Customer favorite',description:'Espresso, creamy oat milk and a touch of honey.'},
  {id:'cold-brew',name:'Cold Brew',category:'coffee',price:4.75,icon:'🧊',tag:'Slow steeped',description:'Cool, smooth and ready for the day.'},
  {id:'matcha',name:'Iced Matcha',category:'tea',price:5.5,icon:'🍵',tag:'Refreshing',description:'Earthy matcha poured over ice and milk.'},
  {id:'chai',name:'Spiced Chai',category:'tea',price:4.75,icon:'🫖',tag:'Cozy choice',description:'Warm spices and silky steamed milk.'},
  {id:'lemonade',name:'House Lemonade',category:'tea',price:4.25,icon:'🍋',tag:'Fresh & bright',description:'A bright, citrusy afternoon refresher.'},
  {id:'sandwich',name:'Garden Sandwich',category:'food',price:9.5,icon:'🥪',tag:'Vegetarian',description:'Seasonal vegetables, herbed spread and sourdough.'},
  {id:'toast',name:'Avocado Toast',category:'food',price:10.5,icon:'🥑',tag:'Vegetarian',description:'Smashed avocado, chili flakes and lemon.'},
  {id:'bowl',name:'Harvest Bowl',category:'food',price:12.5,icon:'🥗',tag:'Vegetarian',description:'Grains, greens and a tangy house dressing.'},
  {id:'croissant',name:'Butter Croissant',category:'bakery',price:4.25,icon:'🥐',tag:'Baked fresh',description:'Golden, flaky and wonderful with coffee.'},
  {id:'muffin',name:'Blueberry Muffin',category:'bakery',price:4.5,icon:'🫐',tag:'Baked fresh',description:'Soft crumb with plenty of blueberries.'},
  {id:'cookie',name:'Chocolate Cookie',category:'bakery',price:3.75,icon:'🍪',tag:'Sweet treat',description:'A soft-centered café classic.'}
];
const money = amount => `$${amount.toFixed(2)}`;
const cartKey = 'juniper-demo-cart'; const ordersKey = 'juniper-demo-orders';
const getCart = () => { try { const value = JSON.parse(localStorage.getItem(cartKey)||'{}'); return value && typeof value === 'object' ? value : {}; } catch { return {}; } };
const saveCart = cart => { localStorage.setItem(cartKey, JSON.stringify(cart)); renderCart(); };
const menuGrid = document.getElementById('menu-grid');
function renderMenu(filter='all') { menuGrid.replaceChildren(); products.filter(p=>filter==='all'||p.category===filter).forEach(p=>{ const card=document.createElement('article');card.className='product-card'; const visual=document.createElement('div');visual.className=`product-visual ${p.category}`;visual.textContent=p.icon; const body=document.createElement('div');body.className='product-body'; const tag=document.createElement('span');tag.className='product-tag';tag.textContent=p.tag; const title=document.createElement('h3');title.textContent=p.name; const desc=document.createElement('p');desc.textContent=p.description;const row=document.createElement('div');row.className='product-row';const price=document.createElement('strong');price.textContent=money(p.price);const add=document.createElement('button');add.type='button';add.className='add-button';add.setAttribute('aria-label',`Add ${p.name} to order`);add.textContent='Add +';add.addEventListener('click',()=>{const cart=getCart();cart[p.id]=(cart[p.id]||0)+1;saveCart(cart);openCart();});row.append(price,add);body.append(tag,title,desc,row);card.append(visual,body);menuGrid.appendChild(card);});}
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false')});button.classList.add('active');button.setAttribute('aria-pressed','true');renderMenu(button.dataset.filter)}));
const drawer=document.getElementById('cart-drawer'), backdrop=document.getElementById('drawer-backdrop');
function openCart(){drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');backdrop.hidden=false;document.body.classList.add('drawer-open');document.getElementById('close-cart').focus()}
function closeCart(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');backdrop.hidden=true;document.body.classList.remove('drawer-open');document.getElementById('open-cart').focus()}
document.getElementById('open-cart').addEventListener('click',openCart);document.getElementById('footer-cart').addEventListener('click',openCart);document.getElementById('close-cart').addEventListener('click',closeCart);backdrop.addEventListener('click',closeCart);document.addEventListener('keydown',event=>{if(event.key==='Escape'&&drawer.classList.contains('open'))closeCart()});
function renderCart(){const cart=getCart(),items=document.getElementById('cart-items');items.replaceChildren();let total=0,count=0;products.forEach(p=>{const qty=Number(cart[p.id])||0;if(qty<=0)return;count+=qty;total+=qty*p.price;const row=document.createElement('div');row.className='cart-item';const info=document.createElement('div');const name=document.createElement('strong');name.textContent=p.name;const detail=document.createElement('span');detail.textContent=`${money(p.price)} each`;info.append(name,detail);const controls=document.createElement('div');controls.className='qty';const minus=document.createElement('button');minus.type='button';minus.textContent='−';minus.setAttribute('aria-label',`Remove one ${p.name}`);minus.addEventListener('click',()=>{const next=getCart();next[p.id]=Math.max(0,(next[p.id]||0)-1);saveCart(next)});const number=document.createElement('span');number.textContent=qty;const plus=document.createElement('button');plus.type='button';plus.textContent='+';plus.setAttribute('aria-label',`Add one ${p.name}`);plus.addEventListener('click',()=>{const next=getCart();next[p.id]=(next[p.id]||0)+1;saveCart(next)});controls.append(minus,number,plus);row.append(info,controls);items.appendChild(row)});if(!count){const empty=document.createElement('p');empty.className='empty-cart';empty.textContent='Your order is empty. Pick something delicious from the menu.';items.appendChild(empty)}document.getElementById('cart-count').textContent=count;document.getElementById('cart-total').textContent=money(total);document.querySelector('#order-form button[type="submit"]').disabled=!count;}
document.getElementById('order-form').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;const cart=getCart();const items=products.filter(p=>cart[p.id]>0).map(p=>({id:p.id,name:p.name,quantity:cart[p.id],price:p.price}));if(!items.length)return;const data=Object.fromEntries(new FormData(form));const order={id:Date.now(),name:data.name.trim(),time:data.time,items,total:items.reduce((sum,item)=>sum+item.quantity*item.price,0),status:'New',created:new Date().toISOString()};try{const orders=JSON.parse(localStorage.getItem(ordersKey)||'[]');orders.unshift(order);localStorage.setItem(ordersKey,JSON.stringify(orders));localStorage.removeItem(cartKey);form.reset();renderCart();document.getElementById('order-message').textContent='Demo order saved in this browser. View it on the owner dashboard.';}catch{document.getElementById('order-message').textContent='This browser could not save the order. Please enable local storage and try again.'}});
const toggle=document.querySelector('.menu-toggle'),nav=document.getElementById('main-nav');toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));toggle.setAttribute('aria-label',open?'Open menu':'Close menu');nav.classList.toggle('open',!open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));document.getElementById('year').textContent=new Date().getFullYear();renderMenu();renderCart();
