const trips=[
 {name:'Bali, Indonesia',type:'beach',emoji:'🌴',days:'7 days',price:1290,label:'ISLAND TIME',description:'Sunlit beaches, green terraces and a little time to breathe.',color:'bali'},
 {name:'Kyoto, Japan',type:'culture',emoji:'⛩️',days:'6 days',price:1580,label:'CULTURE & CALM',description:'Historic lanes, gardens and unforgettable food.',color:'kyoto'},
 {name:'Swiss Alps, Switzerland',type:'nature',emoji:'🏔️',days:'8 days',price:2190,label:'MOUNTAIN AIR',description:'Scenic rail journeys and beautiful alpine walks.',color:'alps'},
 {name:'Amalfi Coast, Italy',type:'beach',emoji:'🍋',days:'6 days',price:1890,label:'COASTAL CHARM',description:'Colorful towns, sea views and slow afternoons.',color:'amalfi'},
 {name:'South Island, New Zealand',type:'nature',emoji:'🚞',days:'10 days',price:2890,label:'BIG ADVENTURE',description:'Lakes, landscapes and wide-open discovery.',color:'zealand'},
 {name:'Marrakech, Morocco',type:'culture',emoji:'🕌',days:'5 days',price:1190,label:'CITY COLORS',description:'Markets, courtyards and a taste of something new.',color:'morocco'}
];
const grid=document.getElementById('trip-grid');function renderTrips(filter='all'){grid.replaceChildren();trips.filter(t=>filter==='all'||t.type===filter).forEach(t=>{const card=document.createElement('article');card.className='trip-card';const visual=document.createElement('div');visual.className=`trip-visual ${t.color}`;const photo=document.createElement('img');photo.src=`images/${t.color}.webp`;photo.alt=t.name;photo.loading='lazy';visual.appendChild(photo);const body=document.createElement('div');body.className='trip-body';const label=document.createElement('span');label.className='trip-label';label.textContent=t.label;const name=document.createElement('h3');name.textContent=t.name;const desc=document.createElement('p');desc.textContent=t.description;const foot=document.createElement('div');foot.className='trip-foot';const price=document.createElement('span');price.textContent=`${t.days} · From $${t.price.toLocaleString()} / person`;const button=document.createElement('button');button.type='button';button.textContent='Enquire →';button.setAttribute('aria-label',`Enquire about ${t.name}`);button.addEventListener('click',()=>{document.getElementById('destination-select').value=t.name;document.getElementById('plan').scrollIntoView({behavior:'smooth'});document.getElementById('destination-select').focus({preventScroll:true})});foot.append(price,button);body.append(label,name,desc,foot);card.append(visual,body);grid.appendChild(card)})}document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-pressed','false')});b.classList.add('active');b.setAttribute('aria-pressed','true');renderTrips(b.dataset.filter)}));
const toggle=document.querySelector('.menu-toggle'),nav=document.getElementById('site-nav');toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')==='true';toggle.setAttribute('aria-expanded',String(!open));toggle.setAttribute('aria-label',open?'Open menu':'Close menu');nav.classList.toggle('open',!open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));
const monthInput=document.querySelector('input[name="month"]');monthInput.min=new Date().toISOString().slice(0,7);
document.getElementById('enquiry-form').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form));const enquiry={id:Date.now(),name:data.name.trim(),email:data.email.trim(),destination:data.destination,travelers:Number(data.travelers),month:data.month,budget:data.budget,style:data.style,status:'New',created:new Date().toISOString()};try{const key='northstar-demo-enquiries';const list=JSON.parse(localStorage.getItem(key)||'[]');list.unshift(enquiry);localStorage.setItem(key,JSON.stringify(list));form.reset();document.getElementById('form-message').textContent='Demo enquiry saved in this browser. Open the owner dashboard to view it.'}catch{document.getElementById('form-message').textContent='This browser could not save the enquiry. Please enable local storage and try again.'}});
document.getElementById('year').textContent=new Date().getFullYear();renderTrips();
